//! This file was generated by `generate_ranges/gen.py` from the Unicode {VERSION} specification.  For an in-depth discussion on how this file is generated, see https://github.com/jameslanska/unicode-display-width/blob/main/hex_range_generation.md

/// Inclusive hexadecimal range of Unicode code points
pub type CodePointRange = std::ops::RangeInclusive<u32>;

/// Simple ASCII characters - used a lot, so we check them first.
pub const ASCII_TABLE: &[CodePointRange] = &[0x00020..=0x0007E];

/// Width 2 characters.
pub const DOUBLEWIDE_TABLE: &[CodePointRange] = &[
    // {RANGES}
];
